### PR TITLE
update iOS receive sharing intent to not suppress link propagation to other modules

### PR DESCRIPTION
**Pull request by danReynolds**
First off, really thankful for this plugin, it provides much needed functionality for my app and others.

As discussed in https://github.com/KasemJaffer/receive_sharing_intent/issues/54, the plugin is currently suppressing link events meant for other modules. A good example of this are firebase deep links, which are being suppressed on both app launch and resume because of how we are processing the application functions.

This PR updates the way we process events to:

1. Only process them if they have a matching custom scheme as the one we're expecting (ShareMedia)
2. Give other modules the chance to process them if they are not our custom scheme

This is the way I see it being handled in similar functionality provided by libraries like [flutterfire](https://github.com/FirebaseExtended/flutterfire/blob/6e4302a68bdc0b0c758528e99f06466fde98f404/packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m#L150) and the [firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk/blob/62735099d51778e43f15adc8f0057b7c8d72e17b/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L456) where they only swallow the event if it is relevant to the scheme they're able to handle.

The changes are called out in comments for each relevant function. I would definitely advise folks to either include this change or run their own similar one since deep links are essential to a lot of apps and it was a bit of a hard bug to track down for someone like myself who doesn't do much Swift programming in my day-to-day.

### CODE REVIEW

**Comment by GRBurst** [comment]
This PR looks good to me. I was facing the same issue. Testing it right now but the PR describes the issue pretty accurate :+1:

**Review by GRBurst — APPROVED** [review]

**Comment by luismarquesfreire** [comment]
Please merge this PR, this is simple but really necessary

**Comment by KasemJaffer** [comment]
Thank you @danReynolds for the well documented PR... I just published `v1.4.3` with this PR included.

**Comment by woutervanwijk** [comment]
This patch has some problems for ios sharing of text. See https://github.com/`KasemJaffer/receive_sharing_intent/issues/116# 

Problem is I guess that hasMatchingSchemePrefix blocks all shared text. If I remove that or I remove the "ShareMedia" from line 10:
`private var customSchemePrefix = "";`

it works again. But with these changes, sometimes if I share an url from Safari, Safari crashes #24 

This behaviour was not in 1.4.2

**Comment by Bingbing0311** [comment]
@KasemJaffer There are still issues with version 1.4.3

   public func application(_ application: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        if (hasMatchingSchemePrefix(url: url)) {
            return handleUrl(url: url, setInitialData: false)
        }
        return true///Change to false to avoid other intent handling
    }

**Pull request merged**
