### PR TITLE
fix kotlin build problem

### PR DESCRIPTION
**Pull request by LazyDave76**
Build fails for android because of nullability.

### CODE REVIEW

**Comment by LazyDave76** [comment]
included https://github.com/KasemJaffer/receive_sharing_intent/pull/140

**Comment by KasemJaffer** [comment]
Fixed in later versions

**Comment by proninyaroslav** [comment]
@KasemJaffer 
No. 1.4.4 also crashes on build:
```
e: /home/yaroslav/.pub-cache/hosted/pub.dartlang.org/receive_sharing_intent-1.4.4/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (146, 78): Type mismatch: inferred type is Uri? but Uri was expected
e: /home/yaroslav/.pub-cache/hosted/pub.dartlang.org/receive_sharing_intent-1.4.4/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (207, 95): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?
```

**Comment by kaboc** [comment]
@KasemJaffer 
The issue still exists. I think the changes by @LazyDave76 should be reviewed and merged.
It doesn't look nice that you just closed this issue without respecting his contribution.

**Comment by LazyDave76** [comment]
> @KasemJaffer
> The issue still exists. I think the changes by @LazyDave76 should be reviewed and merged.
> It doesn't look nice that you just closed this issue without respecting his contribution.

Thanks for the support @kaboc :)  I was surprised to see it closed too - I fixed bugs in iOS _and_ Android.

@proninyaroslav copied and opened the pull request https://github.com/KasemJaffer/receive_sharing_intent/pull/145 maybe that one will be approved.

**Comment by gerken-tss** [comment]
@KasemJaffer 
This is still an issue! Please merge this!

**Pull request closed without merging**
