### PR TITLE
Handle screenshot image

### PR DESCRIPTION
**Pull request by armanim**
#279 Handle UIImage (screenshot image) as data url

### CODE REVIEW

**Comment by armanim** [comment]
The current iOS version does not handle intent data received as `UIImage`, thus the host app does not receive screenshot image data. The underlying issue is that the current version can only handle URLs as text or URLs pointing to storage files. However, `UIImage`, being an in-memory file, is not supported.

**Comment by mostafasany** [comment]
When can we merge this PR?

**Comment by YashSavsani** [comment]
Is this branch getting merged? I face an issue when sharing screenshot in IOS. Receiver doesn't receive any file in listener.

**Comment by kasemj** [comment]
> When can we merge this PR?

Another PR has been merged and included in v1.8.0

**Comment by KasemJaffer** [comment]
> When can we merge this PR?

Another PR has been merged and included in v1.8.0

**Pull request closed without merging**
